### ISSUE TITLE
Review: InsertBancnoteForm.jsx

### ISSUE THREAD

**Issue by sevenns** [AlexandrVinogradov/vending-machine-react#2]
**Path:** `src/componets/InsertBancnoteForm/InsertBancnoteForm.jsx`

- Again `<>`?
  - Line link: https://github.com/AlexandrVinogradov/vending-machine-react/blob/03615ff6af835928922ce5a5bac9bfaf04ba7ae8/src/componets/InsertBancnoteForm/InsertBancnoteForm.jsx#L4

- Again nested ternary.
  - Line link: https://github.com/AlexandrVinogradov/vending-machine-react/blob/03615ff6af835928922ce5a5bac9bfaf04ba7ae8/src/componets/InsertBancnoteForm/InsertBancnoteForm.jsx#L8

- Typo in *Bancnote* 😏

**Comment by AlexandrVinogradov** [comment]
Created pull request with fix
[link](https://github.com/AlexandrVinogradov/vending-machine-react/pull/5)
